import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// @ts-ignore
import { JSDOM } from 'jsdom';

globalThis.DOMParser = class {
    parseFromString(string: string, contentType: string) {
        return new JSDOM(string, {
            contentType,
        }).window.document;
    }
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
